name: Android Cloud Automation

on:
workflow_dispatch:

jobs:
android-test:
runs-on: ubuntu-latest

steps:
  - name: Checkout Repository
    uses: actions/checkout@v4

  - name: Start Android Emulator
    uses: reactivecircus/android-emulator-runner@v2
    with:
      api-level: 34
      arch: x86_64
      profile: pixel_7

      script: |
        adb devices

        adb install apk/app.apk

        adb shell monkey -p com.web.messenger.dual.chat -c android.intent.category.LAUNCHER 1

        sleep 30

        adb shell screencap -p /sdcard/screen.png

        adb pull /sdcard/screen.png
